const fs = require('fs');
const path = require('path');

// Define the directory where HTML files are stored
const directoryPath = 'course';

// List of URLs you want to remove
const urlsToRemove = [
  'automation-testing-course-in-dharmavaram.html',
  'automation-testing-course-in-erode.html',
  'business-analyst-training-course-in-amravati.html',
  'cyber-security-training-course-in-gandhinagar.html',
  'data-analytics-training-course-in-agartala.html',
  'data-analytics-training-course-in-ahmednagar.html',
  'data-analytics-training-course-in-akola.html',
  'data-analytics-training-course-in-ambala.html',
  'data-analytics-training-course-in-ambattur.html',
  'data-analytics-training-course-in-ambernath.html',
  'data-analytics-training-course-in-amroha.html',
  'data-analytics-training-course-in-anand.html',
  'data-analytics-training-course-in-arrah.html',
  'data-analytics-training-course-in-australia.html',
  'data-analytics-training-course-in-baharampur.html',
  'data-analytics-training-course-in-bahraich.html',
  'data-analytics-training-course-in-bally.html',
  'data-analytics-training-course-in-baranagar.html',
  'data-analytics-training-course-in-bathinda.html',
  'data-analytics-training-course-in-belgaum.html',
  'data-analytics-training-course-in-bellary.html',
  'data-analytics-training-course-in-berhampur.html',
  'data-analytics-training-course-in-bhagalpur.html',
  'data-analytics-training-course-in-bhalswa-jahangir-pur.html',
  'data-analytics-training-course-in-bharatpur.html',
  'data-analytics-training-course-in-bhatpara.html',
  'data-analytics-training-course-in-bhavnagar.html',
  'data-analytics-training-course-in-bhilwara.html',
  'data-analytics-training-course-in-bhiwandi.html',
  'data-analytics-training-course-in-bhiwani.html',
  'data-analytics-training-course-in-bidar.html',
  'data-analytics-training-course-in-bijapur.html',
  'data-analytics-training-course-in-bokaro.html',
  'data-analytics-training-course-in-bulandshahr.html',
  'data-analytics-training-course-in-canada.html',
  'data-analytics-training-course-in-chandrapur.html',
  'data-analytics-training-course-in-chapra.html',
  'data-analytics-training-course-in-chittoor.html',
  'data-analytics-training-course-in-cuddalore.html',
  'data-analytics-training-course-in-cuttack.html',
  'data-analytics-training-course-in-danapur.html',
  'data-analytics-training-course-in-darbhanga.html',
  'data-analytics-training-course-in-davanagere.html',
  'data-analytics-training-course-in-deoghar.html',
  'data-analytics-training-course-in-dharmavaram.html',
  'data-analytics-training-course-in-dhule.html',
  'data-analytics-training-course-in-etawah.html',
  'data-analytics-training-course-in-farrukhabad.html',
  'data-analytics-training-course-in-fatehpur.html',
  'data-analytics-training-course-in-gandhidham.html',
  'data-analytics-training-course-in-gopalpur.html',
  'data-analytics-training-course-in-gulbarga.html',
  'data-analytics-training-course-in-guntakal.html',
  'data-analytics-training-course-in-haldia.html',
  'data-analytics-training-course-in-hapur.html',
  'data-analytics-training-course-in-hooghly.html',
  'data-analytics-training-course-in-hoshiarpur.html',
  'data-analytics-training-course-in-hospet.html',
  'data-analytics-training-course-in-hubballi-dharwad.html',
  'data-analytics-training-course-in-ichalkaranji.html',
  'data-analytics-training-course-in-imphal.html',
  'data-analytics-training-course-in-ireland.html',
  'data-analytics-training-course-in-jalandhar.html',
  'data-analytics-training-course-in-jalgaon.html',
  'data-analytics-training-course-in-jammu.html',
  'data-analytics-training-course-in-jamnagar.html',
  'data-analytics-training-course-in-jamshedpur.html',
  'data-analytics-training-course-in-jehanabad.html',
  'data-analytics-training-course-in-jhansi.html',
  'data-analytics-training-course-in-jodhpur.html',
  'data-analytics-training-course-in-kamarhati.html',
  'data-analytics-training-course-in-kannur.html',
  'data-analytics-training-course-in-karnal.html',
  'data-analytics-training-course-in-karur.html',
  'data-analytics-training-course-in-kenya.html',
  'data-analytics-training-course-in-khammam.html',
  'data-analytics-training-course-in-khandwa.html',
  'data-analytics-training-course-in-khappam.html',
  'data-analytics-training-course-in-khora.html',
  'data-analytics-training-course-in-khordha.html',
  'data-analytics-training-course-in-kolhapur.html',
  'data-analytics-training-course-in-kozhikode.html',
  'data-analytics-training-course-in-krishnanagar.html',
  'data-analytics-training-course-in-kulti.html',
  'data-analytics-training-course-in-london.html',
  'data-analytics-training-course-in-madurai.html',
  'data-analytics-training-course-in-malappuram.html',
  'data-analytics-training-course-in-malaysia.html',
  'data-analytics-training-course-in-malegaon.html',
  'data-analytics-training-course-in-mangalore.html',
  'data-analytics-training-course-in-mehsana.html',
  'data-analytics-training-course-in-morena.html',
  'data-analytics-training-course-in-munger.html',
  'data-analytics-training-course-in-murshidabad.html',
  'data-analytics-training-course-in-muzaffarpur.html',
  'data-analytics-training-course-in-mysore.html',
  'data-analytics-training-course-in-nadiad.html',
  'data-analytics-training-course-in-nagercoil.html',
  'data-analytics-training-course-in-naihati.html',
  'data-analytics-training-course-in-namakkal.html',
  'data-analytics-training-course-in-nandyal.html',
  'data-analytics-training-course-in-nellore.html',
  'data-analytics-training-course-in-netherlands.html',
  'data-analytics-training-course-in-nigeria.html',
  'data-analytics-training-course-in-north-dumdum.html',
  'data-analytics-training-course-in-ongole.html',
  'data-analytics-training-course-in-orai.html',
  'data-analytics-training-course-in-ozhukarai.html',
  'data-analytics-training-course-in-palakkad.html',
  'data-analytics-training-course-in-pali.html',
  'data-analytics-training-course-in-palwal.html',
  'data-analytics-training-course-in-panchkula.html',
  'data-analytics-training-course-in-panvel.html',
  'data-analytics-training-course-in-parbhani.html',
  'data-analytics-training-course-in-perambalur.html',
  'data-analytics-training-course-in-pondicherry.html',
  'data-analytics-training-course-in-puducherry.html',
  'data-analytics-training-course-in-pudukkottai.html',
  'data-analytics-training-course-in-purnia.html',
  'data-analytics-training-course-in-raipur.html',
  'data-analytics-training-course-in-rajkot.html',
  'data-analytics-training-course-in-ramagundam.html',
  'data-analytics-training-course-in-rampur.html',
  'data-analytics-training-course-in-ratlam.html',
  'data-analytics-training-course-in-ratnagiri.html',
  'data-analytics-training-course-in-rourkela.html',
  'data-analytics-training-course-in-sagar.html',
  'data-analytics-training-course-in-saharanpur.html',
  'data-analytics-training-course-in-salem.html',
  'data-analytics-training-course-in-sambalpur.html',
  'data-analytics-training-course-in-secunderabad.html',
  'data-analytics-training-course-in-shimla.html',
  'data-analytics-training-course-in-sikar.html',
  'data-analytics-training-course-in-siliguri.html',
  'data-analytics-training-course-in-singrauli.html',
  'data-analytics-training-course-in-sirmaur.html',
  'data-analytics-training-course-in-siwan.html',
  'data-analytics-training-course-in-solan.html',
  'data-analytics-training-course-in-solapur.html',
  'data-analytics-training-course-in-south-africa.html',
  'data-analytics-training-course-in-sri-lanka.html',
  'data-analytics-training-course-in-srinagar.html',
  'data-analytics-training-course-in-tadipatri.html',
  'data-analytics-training-course-in-tenali.html',
  'data-analytics-training-course-in-thanjavur.html',
  'data-analytics-training-course-in-thiruvallur.html',
  'data-analytics-training-course-in-thoothukudi.html',
  'data-analytics-training-course-in-tirupati.html',
  'data-analytics-training-course-in-tiruppur.html',
  'data-analytics-training-course-in-tiruvannamalai.html',
  'data-analytics-training-course-in-vellore.html',
  'data-analytics-training-course-in-vijayanagaram.html',
  'data-analytics-training-course-in-vijayawada.html',
  'data-analytics-training-course-in-visakhapatnam.html',
  'data-analytics-training-course-in-vizianagaram.html',
  'data-science-training-course-in-bikaner.html',
  'data-science-training-course-in-burhanpur.html',
  'data-science-training-course-in-darbhanga.html',
  'data-science-training-course-in-etawah.html',
  'data-science-training-course-in-hapur.html',
  'data-science-training-course-in-haridwar.html',
  'data-science-training-course-in-hospet.html',
  'data-science-training-course-in-kottayam.html',
  'data-science-training-course-in-mahesana.html',
  'data-science-training-course-in-nagarcoil.html',
  'data-science-training-course-in-rourkela.html',
  'data-science-training-course-in-saharanpur.html',
  'data-science-training-course-in-sri-ganganagar.html',
  'data-science-training-course-in-thiruvananthapuram.html',
  'data-science-training-course-in-tiruvottiyur.html',
  'data-structure-and-algorithm-training-course-in-chandrapur.html',
  'data-structure-and-algorithm-training-course-in-murwara.html',
  'digital-marketing-course-in-dehri.html',
  'digital-marketing-course-in-sasaram.html',
  'digital-marketing-training-course-in-bhiwani.html',
  'digital-marketing-training-course-in-bidar.html',
  'digital-marketing-training-course-in-bilaspur.html',
  'digital-marketing-training-course-in-cuttack.html',
  'digital-marketing-training-course-in-jamshedpur.html',
  'digital-marketing-training-course-in-nagarcoil.html',
  'digital-marketing-training-course-in-panchkula.html',
  'digital-marketing-training-course-in-prayagraj.html',
  'digital-marketing-training-course-in-saharanpur.html',
  'digital-marketing-training-course-in-sultan-pur-majra.html',
  'full-stack-development-training-course-in-bareily.html',
  'full-stack-development-training-course-in-calicut.html',
  'full-stack-development-training-course-in-gopalpur.html',
  'full-stack-development-training-course-in-imphal.html',
  'full-stack-development-training-course-in-pallavaram.html',
  'full-stack-development-training-course-in-palwal.html',
  'full-stack-development-training-course-in-raurkela-industrial-township.html',
  'full-stack-development-training-course-in-saharanpur.html',
  'full-stack-development-training-course-in-shahjahanpur.html',
  'full-stack-development-training-course-in-solan.html',
  'java-training-course-in-sri-lanka.html',
  'mern-stack-development-training-course-in-maheshtala.html',
  'react-js-training-course-in-chandrapur.html',
  'react-js-training-course-in-durg.html',
  'react-js-training-course-in-namakkal.html',
  'react-js-training-course-in-sikar.html',
  'react-js-training-course-in-suryapet.html',
  'sap-fico-training-course-in-guna.html',
  'seo-training-course-in-avadi.html',
  'seo-training-course-in-hajipur.html',
  'software-testing-training-course-in-bettiah.html',
  'software-testing-training-course-in-cuttack.html',
  'software-testing-training-course-in-danapur.html',
  'software-testing-training-course-in-pimpri-chinchwad.html',
  'software-testing-training-course-in-shivamogga.html',
  'web-designing-training-course-in-belgaum.html',
];

// Arrays to store the results
let deletedUrls = [];
let failedUrls = [];

// Function to delete files and track results
urlsToRemove.forEach((url) => {
  const filePath = path.join(directoryPath, url);

  // Check if the file exists
  if (fs.existsSync(filePath)) {
    fs.unlink(filePath, (err) => {
      if (err) {
        failedUrls.push(url); // If there's an error, push to failed list
        console.error(`Failed to delete ${url}: ${err.message}`);
      } else {
        deletedUrls.push(url); // If successfully deleted, push to success list
        console.log(`Successfully deleted: ${url}`);
      }
    });
  } else {
    failedUrls.push(url); // File doesn't exist, mark it as failed
    console.log(`File not found: ${url}`);
  }
});

// Listen for the process exit to show final results
process.on('exit', () => {
  // Log the successfully deleted files and their count
  console.log(`\nSuccessfully deleted files (${deletedUrls.length}):`);
  console.log(deletedUrls.join('\n') || 'No files deleted');

  // Log the files that failed to delete and their count
  console.log(`\nFailed to delete files (${failedUrls.length}):`);
  console.log(failedUrls.join('\n') || 'No files failed to delete');
});